version: "3"

services:
  iars-dev-minio:
    container_name: iars-dev-minio
    image: minio/minio:RELEASE.2022-09-17T00-09-45Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - .data/minio:/data
    command: server --console-address ":9001" /data
  iars-dev-mediaupload:
    container_name: iars-dev-mediaupload
    build:
      dockerfile: configurations/docker/Dockerfile-maven-debug
      context: ../../
    restart: always
    ports:
      - "9080:9080"
    volumes:
      - ../../src:/usr/src/app/src
      - .data/target:/usr/src/app/target
      - ${HOME}/.m2:/root/.m2