version: "3"

services:
  iars-minio:
    container_name: iars-minio
    image: minio/minio:RELEASE.2022-09-17T00-09-45Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - .data/minio:/data
    command: server --console-address ":9001" /data
  iars-incident:
    container_name: iars-incident
    build:
      dockerfile: Dockerfile-maven
    restart: always
    environment:
      - USE_SQLITE=True
    ports:
      - "8080:8080"
    volumes:
      - ../../src:/app:rw