 _format_version: "1.1"
 _transform: true

 services:
 - host: mockbin.org
   name: example_service
   port: 80
   protocol: http
   routes:
   - name: example_route
     paths:
     - /mock
     strip_path: true
# - host: localhost
#   name: incident_service
#   port: 9080
#   protocol: http
#   routes:
#   - name: some_route
#     paths:
#     - /something
#     strip_path: false
    