 _format_version: "1.1"
 _transform: true

 services:
  - name: incident_service
    host: 10.38.20.101 #iars-kong
    port: 20080
    protocol: http
    routes:
    - name: incidents
      paths:
      - /incident
      strip_path: false
  
  - name: media_service
    host: 10.38.20.101 #iars-kong
    port: 9080
    routes: 
    - name: media
      paths:
      - /media
      strip_path: false
    